#!/usr/bin/env bash
set -euxo pipefail
tdnf update -y
tdnf install -y ca-certificates
tdnf install -y openssl-c_rehash
TRUSTED_CERT="-----BEGIN CERTIFICATE-----
MIIC9TCCAd2gAwIBAgIRAOWq4wlqxN8A+aUg1uL4VUowDQYJKoZIhvcNAQELBQAw
FDESMBAGA1UEAxMJaGFyYm9yLWNhMB4XDTIwMTExOTAzNTgwMloXDTIxMTExOTAz
NTgwMlowFDESMBAGA1UEAxMJaGFyYm9yLWNhMIIBIjANBgkqhkiG9w0BAQEFAAOC
AQ8AMIIBCgKCAQEAzZiW66ns8lDRKJb6DbOASphwZfjaU7a4rYCipRj+5bjNqWq2
eFq6GYN5fn02JX5gYNbSe3LgUTiyEEhBsm6ArOyJrslfajt3UnjLaTVk8zP98WtM
/JLhKhfsCiArxH7zZ8uRS9huEq7GpEPvhrpZh90XRg13BBGXrfoTVXF8vDfliunX
ixbAYDH5dlwHz3abIioMUMfclIqfWv//eGCHe9+0V8kSRtBKAcl4rrldBp0yy0iV
zmMwHXEQq+nPHnQlDwzgCto+VG0K+7FELNWjiXBWAxOY8jibiPK/Y3abJAwbi8Um
/jHJMSD49M8PiP0Q07N+SjR49b5a7vxouCiagwIDAQABo0IwQDAOBgNVHQ8BAf8E
BAMCAqQwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMA8GA1UdEwEB/wQF
MAMBAf8wDQYJKoZIhvcNAQELBQADggEBAIvtkgzUjIyEy6jBwvUCcABiReNTiahM
cL3jpaOAkZx64/MAMibFB0xwJK5E7TYNYXLuXgoPtDUfnnyWUpbQ7k8S4uL2kqbx
XA6L5LFyhk+BBPT0MUHib+qL6LadwA3kjDyDI/Jvq3kL9haeiUfGiJYLw11xqCea
tE6CoEvOio/sgAcoW1QosCixQyo3cJyC62CQ/lLJ0g/JG0eKvfmJvPXcwJU5MvKD
iFmBVyd0cqTjicgk1b7iqNXPrXq0xyCOzDUv8NNi2udn4vgsI279NP+Et0+RjZAA
xMbSYc8lh2MhMxDl8+9rZdFIDnHQd5y+wxMNjzMp5iglOn78Hn3DHS4=
-----END CERTIFICATE-----
"
echo "$TRUSTED_CERT" > /etc/ssl/certs/my-trusted-cert-2.pem
/usr/bin/rehash_ca_certificates.sh
echo "Finished, restarting containerd"
systemctl restart containerd
echo "done"
